apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: server
  name: server
spec:
  replicas: 6
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - image: task-manager-server
        name: server
        imagePullPolicy: Never
        ports:
        - containerPort: 8191
          name: server
        env:
        - name: MONGO_URL
          value: mongodb://db
        - name: DISABLE_SECURITY
          value: "foo-bar-baz"
